// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module CLA (
C5,GND,VDD,X1,X0,X2,X3,X4,T0,T1,T2,T3,T4,X5 );
output  C5;
input  GND;
input  VDD;
input  X1;
input  X0;
input  X2;
input  X3;
input  X4;
input  T0;
input  T1;
input  T2;
input  T3;
input  T4;
input  X5;
wire net139;
wire VDD;
wire net66;
wire X2;
wire net36;
wire T0;
wire T1;
wire net27;
wire GND;
wire [4:0] \~T ;
wire net91;
wire net111;
wire net92;
wire X0;
wire T2;
wire net87;
wire net103;
wire T4;
wire net83;
wire net99;
wire net17;
wire C5;
wire net23;
wire net37;
wire net61;
wire net51;
wire net109;
wire net95;
wire net33;
wire net100;
wire X1;
wire X3;
wire [5:0] X;
wire X4;
wire net56;
wire net96;
wire T3;
wire X5;
wire net42;
wire net80;
wire net104;
wire net22;

INVX1_s3    
 I45  ( .VDD( VDD ), .Z( C5 ), .A( net80 ), .GND( GND ) );

INVX1_s0    
 I20  ( .VDD( VDD ), .Z( net83 ), .A( net109 ), .GND( GND ) );

INVX1_s0    
 I17  ( .VDD( VDD ), .Z( net87 ), .A( net56 ), .GND( GND ) );

INVX1_s0    
 I16  ( .VDD( VDD ), .Z( net91 ), .A( net92 ), .GND( GND ) );

INVX1_s0    
 I15  ( .VDD( VDD ), .Z( net95 ), .A( net96 ), .GND( GND ) );

INVX1_s0    
 I14  ( .VDD( VDD ), .Z( net99 ), .A( net100 ), .GND( GND ) );

INVX1_s0    
 I4  ( .VDD( VDD ), .Z( net103 ), .A( net104 ), .GND( GND ) );

NOR2X1    
 I24  ( .VDD( VDD ), .Z( net22 ), .A( net27 ), .B( net99 ), .GND( GND ) );

NOR2X1    
 I23  ( .VDD( VDD ), .Z( net27 ), .A( net36 ), .B( net33 ), .GND( GND ) );

NOR2X1    
 I22  ( .VDD( VDD ), .Z( net36 ), .A( net37 ), .B( net95 ), .GND( GND ) );

NOR2X1    
 I21  ( .VDD( VDD ), .Z( net37 ), .A( net42 ), .B( net66 ), .GND( GND ) );

NOR2X1    
 I8  ( .VDD( VDD ), .Z( net42 ), .A( net51 ), .B( net91 ), .GND( GND ) );

NOR2X1    
 I7  ( .VDD( VDD ), .Z( net51 ), .A( net83 ), .B( net61 ), .GND( GND ) );

NOR2X1    
 I6  ( .VDD( VDD ), .Z( net56 ), .A( X[0] ), .B( \~T [0] ), .GND( GND ) );

NOR2X1    
 I3  ( .VDD( VDD ), .Z( net61 ), .A( X[1] ), .B( \~T [1] ), .GND( GND ) );

NOR2X1    
 I2  ( .VDD( VDD ), .Z( net66 ), .A( X[2] ), .B( \~T [2] ), .GND( GND ) );

NOR2X1    
 I1  ( .VDD( VDD ), .Z( net33 ), .A( X[3] ), .B( \~T [3] ), .GND( GND ) );

NOR2X1    
 I0  ( .VDD( VDD ), .Z( net23 ), .A( X[4] ), .B( \~T [4] ), .GND( GND ) );

NOR2X1_s2    
 I26  ( .VDD( VDD ), .Z( net80 ), .A( net17 ), .B( net103 ), .GND( GND ) );
