// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module NAND_P7 (
A,B,VDD,GND,Z );
input  A;
input  B;
input  VDD;
input  GND;
output  Z;
wire VDD;
wire Z;
wire A;
wire GND;
wire B;

NAND2X1    
 I0  ( .VDD( VDD ), .Z( Z ), .A( A ), .B( B ), .GND( GND ) );

NAND_P6    
 I1  ( .VDD( VDD ), .Z( Z ), .A( A ), .B( B ), .GND( GND ) );

endmodule

