// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module Abs (
A1,S0,A0,S1,A2,A3,A4,A5,S5,S4,S3,S2,VDD,GND );
input  A1;
output  S0;
input  A0;
output  S1;
input  A2;
input  A3;
input  A4;
input  A5;
output  S5;
output  S4;
output  S3;
output  S2;
input  VDD;
input  GND;
wire VDD;
wire S5;
wire net25;
wire net16;
wire A1;
wire S0;
wire A0;
wire net15;
wire S4;
wire S3;
wire net21;
wire A2;
wire A4;
wire GND;
wire S1;
wire A5;
wire S2;
wire A3;
wire net20;

BUFX2    
 I41  ( .VDD( VDD ), .Y( net15 ), .A( A0 ), .VSS( GND ) );

AND2X1    
 I30  ( .VDD( VDD ), .Y( net20 ), .A( A2 ), .B( net16 ), .VSS( GND ) );

AND2X1    
 I31  ( .VDD( VDD ), .Y( net21 ), .A( A3 ), .B( net20 ), .VSS( GND ) );

AND2X1    
 I29  ( .VDD( VDD ), .Y( net16 ), .A( A1 ), .B( net15 ), .VSS( GND ) );

AND2X1    
 I32  ( .VDD( VDD ), .Y( net25 ), .A( A4 ), .B( net21 ), .VSS( GND ) );

XOR2X1    
 I27  ( .VDD( VDD ), .Y( S4 ), .A( A4 ), .B( net21 ), .VSS( GND ) );

XOR2X1    
 I28  ( .VDD( VDD ), .Y( S5 ), .A( A5 ), .B( net25 ), .VSS( GND ) );

XOR2X1    
 I26  ( .VDD( VDD ), .Y( S3 ), .A( A3 ), .B( net20 ), .VSS( GND ) );

XOR2X1    
 I24  ( .VDD( VDD ), .Y( S1 ), .A( A1 ), .B( net15 ), .VSS( GND ) );

XOR2X1    
 I25  ( .VDD( VDD ), .Y( S2 ), .A( A2 ), .B( net16 ), .VSS( GND ) );

INVX1    
 I42  ( .VDD( VDD ), .Y( S0 ), .A( A0 ), .VSS( GND ) );

endmodule

