// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module TGX1_P8 (
A,S,\~S ,VDD,GND,Z );
input  A;
input  S;
input  \~S ;
input  VDD;
input  GND;
output  Z;
wire VDD;
wire \~S ;
wire S;
wire Z;
wire A;
wire GND;

TGX1    
 I7  ( .\~S ( \~S  ), .VDD( VDD ), .S( S ), .Z( Z ), .A( A ), .GND( GND ) );

TGX1    
 I6  ( .\~S ( \~S  ), .VDD( VDD ), .S( S ), .Z( Z ), .A( A ), .GND( GND ) );

TGX1    
 I5  ( .\~S ( \~S  ), .VDD( VDD ), .S( S ), .Z( Z ), .A( A ), .GND( GND ) );

TGX1    
 I4  ( .\~S ( \~S  ), .VDD( VDD ), .S( S ), .Z( Z ), .A( A ), .GND( GND ) );

TGX1    
 I3  ( .\~S ( \~S  ), .VDD( VDD ), .S( S ), .Z( Z ), .A( A ), .GND( GND ) );

TGX1    
 I2  ( .\~S ( \~S  ), .VDD( VDD ), .S( S ), .Z( Z ), .A( A ), .GND( GND ) );

TGX1    
 I1  ( .\~S ( \~S  ), .VDD( VDD ), .S( S ), .Z( Z ), .A( A ), .GND( GND ) );

TGX1    
 I0  ( .\~S ( \~S  ), .VDD( VDD ), .S( S ), .Z( Z ), .A( A ), .GND( GND ) );

endmodule

