// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module NOR2X1_p18 (
A,B,VDD,GND,Z );
input  A;
input  B;
input  VDD;
input  GND;
output  Z;
wire VDD;
wire Z;
wire A;
wire B;
wire GND;

NOR2X1_p17    
 I0  ( .VDD( VDD ), .Z( Z ), .A( A ), .B( B ), .GND( GND ) );

NOR2X1    
 I1  ( .VDD( VDD ), .Z( Z ), .A( A ), .B( B ), .GND( GND ) );

endmodule

