// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module INVX32 (
Y,A,VDD,VSS );
output  Y;
input  A;
input  VDD;
input  VSS;
wire \VSS! ;
wire \VDD! ;
wire Y;
wire A;

pmos1v    
 mp0  ( .S( \VDD!  ), .G( A ), .D( Y ), .B( \VDD!  ) );

nmos1v    
 mn0  ( .S( \VSS!  ), .G( A ), .D( Y ), .B( \VSS!  ) );

endmodule

