// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module Abs_Value_Detector (
X1,X2,X3,X4,X5,GND,OUT,T1,T2,T3,T4,VDD,X0,T0 );
input  X1;
input  X2;
input  X3;
input  X4;
input  X5;
input  GND;
output  OUT;
input  T1;
input  T2;
input  T3;
input  T4;
input  VDD;
input  X0;
input  T0;
wire net55;
wire VDD;
wire X3;
wire X0;
wire net52;
wire X1;
wire X4;
wire X2;
wire T2;
wire net54;
wire X5;
wire net050;
wire T3;
wire net56;
wire T4;
wire OUT;
wire GND;
wire net53;
wire T1;
wire T0;

Comparator    
 I6  ( .VDD( VDD ), .M2( net54 ), .M3( net53 ), .T2( T2 ), .M0( net56 ), .T3( T3 ), .M4( net52 ), .T4( T4 ), .OUT( OUT ), .GND( GND ), .T0( T0 ), .T1( T1 ), .M1( net55 ) );

Abs_Detector    
 I24  ( .VDD( VDD ), .O5( net050 ), .O1( net55 ), .A1( X1 ), .A0( X0 ), .O4( net52 ), .A2( X2 ), .A5( X5 ), .A4( X4 ), .O3( net53 ), .O2( net54 ), .O0( net56 ), .GND( GND ), .A3( X3 ) );

endmodule

