// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module Driver (
VDD,GND,T0,T1,T2,T3,T4,X0,X1,X2,X3,X4,X5 );
input  VDD;
input  GND;
output  T0;
output  T1;
output  T2;
output  T3;
output  T4;
output  X0;
output  X1;
output  X2;
output  X3;
output  X4;
output  X5;
wire net47;
wire VDD;
wire net59;
wire X2;
wire T1;
wire GND;
wire T0;
wire net53;
wire net55;
wire net50;
wire X0;
wire T2;
wire T4;
wire net64;
wire net46;
wire net48;
wire net57;
wire net52;
wire net61;
wire net51;
wire net43;
wire net49;
wire net44;
wire net63;
wire net60;
wire X3;
wire net62;
wire X1;
wire X4;
wire net56;
wire net54;
wire T3;
wire X5;
wire net45;
wire net58;

INVX1    
 I21  ( .VDD( VDD ), .Y( net57 ), .A( net47 ), .VSS( GND ) );

INVX1    
 I20  ( .VDD( VDD ), .Y( T4 ), .A( net58 ), .VSS( GND ) );

INVX1    
 I19  ( .VDD( VDD ), .Y( net58 ), .A( net43 ), .VSS( GND ) );

INVX1    
 I18  ( .VDD( VDD ), .Y( net55 ), .A( net45 ), .VSS( GND ) );

INVX1    
 I17  ( .VDD( VDD ), .Y( net54 ), .A( net44 ), .VSS( GND ) );

INVX1    
 I16  ( .VDD( VDD ), .Y( T3 ), .A( net54 ), .VSS( GND ) );

INVX1    
 I15  ( .VDD( VDD ), .Y( T2 ), .A( net55 ), .VSS( GND ) );

INVX1    
 I14  ( .VDD( VDD ), .Y( net56 ), .A( net46 ), .VSS( GND ) );

INVX1    
 I13  ( .VDD( VDD ), .Y( T1 ), .A( net56 ), .VSS( GND ) );

INVX1    
 I12  ( .VDD( VDD ), .Y( T0 ), .A( net57 ), .VSS( GND ) );

INVX1    
 I11  ( .VDD( VDD ), .Y( X4 ), .A( net59 ), .VSS( GND ) );

INVX1    
 I10  ( .VDD( VDD ), .Y( X5 ), .A( net60 ), .VSS( GND ) );

INVX1    
 I9  ( .VDD( VDD ), .Y( net60 ), .A( net48 ), .VSS( GND ) );

INVX1    
 I8  ( .VDD( VDD ), .Y( net59 ), .A( net49 ), .VSS( GND ) );

INVX1    
 I7  ( .VDD( VDD ), .Y( net62 ), .A( net51 ), .VSS( GND ) );

INVX1    
 I6  ( .VDD( VDD ), .Y( net61 ), .A( net50 ), .VSS( GND ) );

INVX1    
 I5  ( .VDD( VDD ), .Y( X3 ), .A( net61 ), .VSS( GND ) );

INVX1    
 I4  ( .VDD( VDD ), .Y( X2 ), .A( net62 ), .VSS( GND ) );

INVX1    
 I3  ( .VDD( VDD ), .Y( net63 ), .A( net52 ), .VSS( GND ) );

INVX1    
 I2  ( .VDD( VDD ), .Y( X1 ), .A( net63 ), .VSS( GND ) );

INVX1    
 I1  ( .VDD( VDD ), .Y( X0 ), .A( net64 ), .VSS( GND ) );

INVX1    
 I0  ( .VDD( VDD ), .Y( net64 ), .A( net53 ), .VSS( GND ) );

vpwl    
 V5  ( .PLUS( net49 ), .MINUS( GND ) );

vpwl    
 V4  ( .PLUS( net48 ), .MINUS( GND ) );

vpwl    
 V10  ( .PLUS( net51 ), .MINUS( GND ) );

vpwl    
 V12  ( .PLUS( net50 ), .MINUS( GND ) );

vpwl    
 V1  ( .PLUS( net52 ), .MINUS( GND ) );

vpwl    
 V0  ( .PLUS( net53 ), .MINUS( GND ) );

vdc    
 V11  ( .PLUS( net43 ), .MINUS( GND ) );

vdc    
 V9  ( .PLUS( net44 ), .MINUS( GND ) );

vdc    
 V8  ( .PLUS( net45 ), .MINUS( GND ) );

vdc    
 V7  ( .PLUS( net46 ), .MINUS( GND ) );

vdc    
 V6  ( .PLUS( net47 ), .MINUS( GND ) );

endmodule

