// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module INVX1_p8 (
A,VDD,GND,Z );
input  A;
input  VDD;
input  GND;
output  Z;
wire VDD;
wire Z;
wire A;
wire GND;

INVX1_p5    
 I0  ( .VDD( VDD ), .Z( Z ), .A( A ), .GND( GND ) );

INVX1    
 I3  ( .VDD( VDD ), .Z( Z ), .A( A ), .GND( GND ) );

INVX1    
 I2  ( .VDD( VDD ), .Z( Z ), .A( A ), .GND( GND ) );

INVX1    
 I1  ( .VDD( VDD ), .Z( Z ), .A( A ), .GND( GND ) );

endmodule

