// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module \3X1MUX_p5  (
A,B,C,VDD,GND,Z );
input  A;
input  B;
input  C;
input  VDD;
input  GND;
output  Z;
wire VDD;
wire C;
wire Z;
wire A;
wire GND;
wire B;

\3X1MUX     
 I4  ( .VDD( VDD ), .C( C ), .Z( Z ), .A( A ), .B( B ), .GND( GND ) );

\3X1MUX     
 I3  ( .VDD( VDD ), .C( C ), .Z( Z ), .A( A ), .B( B ), .GND( GND ) );

\3X1MUX     
 I2  ( .VDD( VDD ), .C( C ), .Z( Z ), .A( A ), .B( B ), .GND( GND ) );

\3X1MUX     
 I1  ( .VDD( VDD ), .C( C ), .Z( Z ), .A( A ), .B( B ), .GND( GND ) );

\3X1MUX     
 I0  ( .VDD( VDD ), .C( C ), .Z( Z ), .A( A ), .B( B ), .GND( GND ) );

endmodule

