// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module CLA_param (
);
wire net099;
wire net035;
wire net139;
wire net66;
wire net031;
wire net032;
wire net052;
wire net36;
wire net043;
wire net27;
wire [4:0] \~T ;
wire net91;
wire \gnd! ;
wire net111;
wire net038;
wire net92;
wire net037;
wire net87;
wire net103;
wire net030;
wire net83;
wire net99;
wire net17;
wire net036;
wire net034;
wire net23;
wire net37;
wire net51;
wire net61;
wire net109;
wire net033;
wire net95;
wire net33;
wire net049;
wire net100;
wire [5:0] X;
wire net96;
wire net56;
wire net027;
wire net42;
wire net80;
wire net104;
wire net22;

NAND2X1_param    
 I19  ( .VDD( net027 ), .Z( net109 ), .A( net139 ), .B( net111 ), .GND( \gnd!  ) );

NAND2X1_param    
 I18  ( .VDD( net027 ), .Z( net111 ), .A( net87 ), .B( X[5] ), .GND( \gnd!  ) );

NAND2X1_param    
 I13  ( .VDD( net027 ), .Z( net104 ), .A( X[4] ), .B( \~T [4] ), .GND( \gnd!  ) );

NAND2X1_param    
 I12  ( .VDD( net027 ), .Z( net100 ), .A( X[3] ), .B( \~T [3] ), .GND( \gnd!  ) );

NAND2X1_param    
 I11  ( .VDD( net027 ), .Z( net96 ), .A( X[2] ), .B( \~T [2] ), .GND( \gnd!  ) );

NAND2X1_param    
 I10  ( .VDD( net027 ), .Z( net92 ), .A( X[1] ), .B( \~T [1] ), .GND( \gnd!  ) );

NAND2X1_param    
 I9  ( .VDD( net027 ), .Z( net139 ), .A( X[0] ), .B( \~T [0] ), .GND( \gnd!  ) );

NOR2X1_param    
 I26  ( .VDD( net027 ), .Z( net80 ), .A( net17 ), .B( net103 ), .GND( \gnd!  ) );

NOR2X1_param    
 I25  ( .VDD( net027 ), .Z( net17 ), .A( net22 ), .B( net23 ), .GND( \gnd!  ) );

NOR2X1_param    
 I24  ( .VDD( net027 ), .Z( net22 ), .A( net27 ), .B( net99 ), .GND( \gnd!  ) );

NOR2X1_param    
 I23  ( .VDD( net027 ), .Z( net27 ), .A( net36 ), .B( net33 ), .GND( \gnd!  ) );

NOR2X1_param    
 I22  ( .VDD( net027 ), .Z( net36 ), .A( net37 ), .B( net95 ), .GND( \gnd!  ) );

NOR2X1_param    
 I21  ( .VDD( net027 ), .Z( net37 ), .A( net42 ), .B( net66 ), .GND( \gnd!  ) );

NOR2X1_param    
 I8  ( .VDD( net027 ), .Z( net42 ), .A( net51 ), .B( net91 ), .GND( \gnd!  ) );

NOR2X1_param    
 I7  ( .VDD( net027 ), .Z( net51 ), .A( net83 ), .B( net61 ), .GND( \gnd!  ) );

NOR2X1_param    
 I6  ( .VDD( net027 ), .Z( net56 ), .A( X[0] ), .B( \~T [0] ), .GND( \gnd!  ) );

NOR2X1_param    
 I3  ( .VDD( net027 ), .Z( net61 ), .A( X[1] ), .B( \~T [1] ), .GND( \gnd!  ) );

NOR2X1_param    
 I2  ( .VDD( net027 ), .Z( net66 ), .A( X[2] ), .B( \~T [2] ), .GND( \gnd!  ) );

NOR2X1_param    
 I1  ( .VDD( net027 ), .Z( net33 ), .A( X[3] ), .B( \~T [3] ), .GND( \gnd!  ) );

NOR2X1_param    
 I0  ( .VDD( net027 ), .Z( net23 ), .A( X[4] ), .B( \~T [4] ), .GND( \gnd!  ) );

Driver    
 I46  ( .VDD( net052 ), .X3( net036 ), .X1( net032 ), .X0( net030 ), .T2( net035 ), .X4( net038 ), .X2( net034 ), .T3( net033 ), .X5( net043 ), .T4( net031 ), .T1( net037 ), .T0( net049 ), .GND( \gnd!  ) );

INVX1_param    
 I51  ( .VDD( net027 ), .Z( net099 ), .A( net80 ), .GND( \gnd!  ) );

INVX1_param    
 I20  ( .VDD( net027 ), .Z( net83 ), .A( net109 ), .GND( \gnd!  ) );

INVX1_param    
 I17  ( .VDD( net027 ), .Z( net87 ), .A( net56 ), .GND( \gnd!  ) );

INVX1_param    
 I16  ( .VDD( net027 ), .Z( net91 ), .A( net92 ), .GND( \gnd!  ) );

INVX1_param    
 I15  ( .VDD( net027 ), .Z( net95 ), .A( net96 ), .GND( \gnd!  ) );

INVX1_param    
 I14  ( .VDD( net027 ), .Z( net99 ), .A( net100 ), .GND( \gnd!  ) );

INVX1_param    
 I4  ( .VDD( net027 ), .Z( net103 ), .A( net104 ), .GND( \gnd!  ) );

vdc    
 V0  ( .PLUS( net052 ), .MINUS( \gnd!  ) );

vdc    
 V1  ( .PLUS( net027 ), .MINUS( \gnd!  ) );

Load    
 I47  ( .VDD( net052 ), .OUT( net099 ), .GND( \gnd!  ) );
