// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module Abs_Detector (
A0,A1,A2,A3,A4,A5,VDD,GND,O0,O1,O2,O3,O4,O5 );
input  A0;
input  A1;
input  A2;
input  A3;
input  A4;
input  A5;
input  VDD;
input  GND;
output  O0;
output  O1;
output  O2;
output  O3;
output  O4;
output  O5;
wire VDD;
wire net47;
wire net29;
wire net029;
wire net031;
wire net34;
wire net032;
wire O4;
wire A0;
wire net36;
wire O2;
wire GND;
wire O3;
wire net028;
wire A3;
wire O1;
wire A1;
wire net030;
wire A4;
wire net46;
wire net37;
wire A2;
wire net033;
wire net32;
wire O0;
wire A5;
wire net33;
wire net31;
wire O5;
wire net35;
wire net45;
wire net30;

Abs    
 I99  ( .S5( net37 ), .VDD( VDD ), .A1( net031 ), .S0( net30 ), .A0( net032 ), .S4( net36 ), .S3( net34 ), .A2( net030 ), .A5( net033 ), .A4( net028 ), .S1( net32 ), .GND( GND ), .A3( net029 ), .S2( net33 ) );

MX2X1    
 I96  ( .VDD( VDD ), .S0( A5 ), .Y( O0 ), .A( net47 ), .B( net30 ), .VSS( GND ) );

MX2X1    
 I91  ( .VDD( VDD ), .S0( A5 ), .Y( O5 ), .A( net46 ), .B( net37 ), .VSS( GND ) );

MX2X1    
 I92  ( .VDD( VDD ), .S0( A5 ), .Y( O4 ), .A( net45 ), .B( net36 ), .VSS( GND ) );

MX2X1    
 I93  ( .VDD( VDD ), .S0( A5 ), .Y( O3 ), .A( net35 ), .B( net34 ), .VSS( GND ) );

MX2X1    
 I94  ( .VDD( VDD ), .S0( A5 ), .Y( O2 ), .A( net31 ), .B( net33 ), .VSS( GND ) );

MX2X1    
 I95  ( .VDD( VDD ), .S0( A5 ), .Y( O1 ), .A( net29 ), .B( net32 ), .VSS( GND ) );

BUFX2    
 I90  ( .VDD( VDD ), .Y( net47 ), .A( A0 ), .VSS( GND ) );

BUFX2    
 I89  ( .VDD( VDD ), .Y( net29 ), .A( A1 ), .VSS( GND ) );

BUFX2    
 I88  ( .VDD( VDD ), .Y( net31 ), .A( A2 ), .VSS( GND ) );

BUFX2    
 I87  ( .VDD( VDD ), .Y( net35 ), .A( A3 ), .VSS( GND ) );

BUFX2    
 I86  ( .VDD( VDD ), .Y( net45 ), .A( A4 ), .VSS( GND ) );

BUFX2    
 I85  ( .VDD( VDD ), .Y( net46 ), .A( A5 ), .VSS( GND ) );

INVX1    
 I108  ( .VDD( VDD ), .Y( net031 ), .A( A1 ), .VSS( GND ) );

INVX1    
 I109  ( .VDD( VDD ), .Y( net030 ), .A( A2 ), .VSS( GND ) );

INVX1    
 I107  ( .VDD( VDD ), .Y( net032 ), .A( A0 ), .VSS( GND ) );

INVX1    
 I110  ( .VDD( VDD ), .Y( net029 ), .A( A3 ), .VSS( GND ) );

INVX1    
 I111  ( .VDD( VDD ), .Y( net028 ), .A( A4 ), .VSS( GND ) );

INVX1    
 I112  ( .VDD( VDD ), .Y( net033 ), .A( A5 ), .VSS( GND ) );

endmodule

