// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module INVX1_s3 (
VDD,A,GND,Z );
input  VDD;
input  A;
input  GND;
output  Z;
wire VDD;
wire Z;
wire A;
wire GND;

nmos1v    
 NM0  ( .S( GND ), .G( A ), .B( GND ), .D( Z ) );

pmos1v    
 PM0  ( .S( VDD ), .G( A ), .B( VDD ), .D( Z ) );

endmodule

