// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module NOR_P14 (
A,B,VDD,GND,Z );
input  A;
input  B;
input  VDD;
input  GND;
output  Z;
wire VDD;
wire Z;
wire A;
wire GND;
wire B;

NOR2X1    
 I13  ( .VDD( VDD ), .Z( Z ), .A( A ), .B( B ), .GND( GND ) );

NOR2X1    
 I12  ( .VDD( VDD ), .Z( Z ), .A( A ), .B( B ), .GND( GND ) );

NOR2X1    
 I11  ( .VDD( VDD ), .Z( Z ), .A( A ), .B( B ), .GND( GND ) );

NOR2X1    
 I10  ( .VDD( VDD ), .Z( Z ), .A( A ), .B( B ), .GND( GND ) );

NOR2X1    
 I9  ( .VDD( VDD ), .Z( Z ), .A( A ), .B( B ), .GND( GND ) );

NOR2X1    
 I8  ( .VDD( VDD ), .Z( Z ), .A( A ), .B( B ), .GND( GND ) );

NOR2X1    
 I7  ( .VDD( VDD ), .Z( Z ), .A( A ), .B( B ), .GND( GND ) );

NOR2X1    
 I6  ( .VDD( VDD ), .Z( Z ), .A( A ), .B( B ), .GND( GND ) );

NOR2X1    
 I5  ( .VDD( VDD ), .Z( Z ), .A( A ), .B( B ), .GND( GND ) );

NOR2X1    
 I4  ( .VDD( VDD ), .Z( Z ), .A( A ), .B( B ), .GND( GND ) );

NOR2X1    
 I3  ( .VDD( VDD ), .Z( Z ), .A( A ), .B( B ), .GND( GND ) );

NOR2X1    
 I2  ( .VDD( VDD ), .Z( Z ), .A( A ), .B( B ), .GND( GND ) );

NOR2X1    
 I1  ( .VDD( VDD ), .Z( Z ), .A( A ), .B( B ), .GND( GND ) );

NOR2X1    
 I0  ( .VDD( VDD ), .Z( Z ), .A( A ), .B( B ), .GND( GND ) );

endmodule

