// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module NOR2X1 (
A,B,GND,Z,VDD );
input  A;
input  B;
input  GND;
output  Z;
input  VDD;
wire VDD;
wire net15;
wire Z;
wire A;
wire B;
wire GND;

nmos1v    
 NM1  ( .S( GND ), .G( A ), .B( GND ), .D( Z ) );

nmos1v    
 NM0  ( .S( GND ), .G( B ), .B( GND ), .D( Z ) );

pmos1v    
 PM1  ( .S( net15 ), .G( B ), .B( VDD ), .D( Z ) );

pmos1v    
 PM0  ( .S( VDD ), .G( A ), .B( VDD ), .D( net15 ) );

endmodule

