// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module NAND_P6 (
A,B,VDD,GND,Z );
input  A;
input  B;
input  VDD;
input  GND;
output  Z;
wire VDD;
wire Z;
wire A;
wire B;
wire GND;

NAND2X1    
 I5  ( .VDD( VDD ), .Z( Z ), .A( A ), .B( B ), .GND( GND ) );

NAND2X1    
 I4  ( .VDD( VDD ), .Z( Z ), .A( A ), .B( B ), .GND( GND ) );

NAND2X1    
 I3  ( .VDD( VDD ), .Z( Z ), .A( A ), .B( B ), .GND( GND ) );

NAND2X1    
 I2  ( .VDD( VDD ), .Z( Z ), .A( A ), .B( B ), .GND( GND ) );

NAND2X1    
 I1  ( .VDD( VDD ), .Z( Z ), .A( A ), .B( B ), .GND( GND ) );

NAND2X1    
 I0  ( .VDD( VDD ), .Z( Z ), .A( A ), .B( B ), .GND( GND ) );

endmodule

