// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module \3X1MUX  (
A,B,GND,VDD,C,Z );
input  A;
input  B;
input  GND;
input  VDD;
input  C;
output  Z;
wire VDD;
wire C;
wire net16;
wire Z;
wire A;
wire B;
wire GND;

TGX1_param    
 I1  ( .\~S ( C ), .VDD( VDD ), .S( net16 ), .Z( Z ), .A( B ), .GND( GND ) );

TGX1_param    
 I0  ( .\~S ( net16 ), .VDD( VDD ), .S( C ), .Z( Z ), .A( A ), .GND( GND ) );

INVX1_param    
 I3  ( .VDD( VDD ), .Z( net16 ), .A( C ), .GND( GND ) );

endmodule

