// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module \3X1MUX  (
A,B,GND,VDD,C,Z );
input  A;
input  B;
input  GND;
input  VDD;
input  C;
output  Z;
wire VDD;
wire C;
wire Z;
wire A;
wire net010;
wire GND;
wire B;

TGX1    
 I1  ( .\~S ( C ), .VDD( VDD ), .S( net010 ), .Z( Z ), .A( B ), .GND( GND ) );

TGX1    
 I0  ( .\~S ( net010 ), .VDD( VDD ), .S( C ), .Z( Z ), .A( A ), .GND( GND ) );

INVX1_s0    
 I3  ( .VDD( VDD ), .Z( net010 ), .A( C ), .GND( GND ) );

endmodule

