// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module INVX1_p5 (
A,Z,VDD,GND );
input  A;
output  Z;
input  VDD;
input  GND;
wire VDD;
wire Z;
wire A;
wire GND;

INVX1    
 I4  ( .VDD( VDD ), .Z( Z ), .A( A ), .GND( GND ) );

INVX1    
 I3  ( .VDD( VDD ), .Z( Z ), .A( A ), .GND( GND ) );

INVX1    
 I2  ( .VDD( VDD ), .Z( Z ), .A( A ), .GND( GND ) );

INVX1    
 I1  ( .VDD( VDD ), .Z( Z ), .A( A ), .GND( GND ) );

INVX1    
 I0  ( .VDD( VDD ), .Z( Z ), .A( A ), .GND( GND ) );

endmodule

